# Generated by Django 5.1.4 on 2024-12-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
