# Generated by Django 5.1.4 on 2024-12-31 08:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0002_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('noteTitle', models.CharField(max_length=200)),
                ('noteContent', models.CharField(max_length=1000)),
                ('createOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateOn', models.DateTimeField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataHandle.userdata')),
            ],
        ),
    ]
